name: power_price_pred
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - scikit-learn=1.2.2
  - sktime=0.20.0
  - lightgbm=3.3.5
  - pytest=7.3.1
  - plotly=5.9.0
  - matplotlib
  - seaborn
  - xgboost
  - pip
  - jupyter-book
  - docopt
  - shap
  - statsmodels=0.14.0
